from .Genesis import genesis_1
from .Genesis import genesis_2
from .Genesis import genesis_3
from .Genesis import genesis_4
from .Genesis import genesis_5
from .Genesis import genesis_6
from .Genesis import genesis_7
from .Genesis import genesis_8
from .Genesis import genesis_9
from .Genesis import genesis_10